//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOTWeek1ClientSide_TextGame.DungeonGame {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://simpleGame/", ConfigurationName="DungeonGame.SimpleDungeon")]
    public interface SimpleDungeon {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://simpleGame/SimpleDungeon/endRequest", ReplyAction="http://simpleGame/SimpleDungeon/endResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SOTWeek1ClientSide_TextGame.DungeonGame.endResponse end(SOTWeek1ClientSide_TextGame.DungeonGame.endRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://simpleGame/SimpleDungeon/endRequest", ReplyAction="http://simpleGame/SimpleDungeon/endResponse")]
        System.Threading.Tasks.Task<SOTWeek1ClientSide_TextGame.DungeonGame.endResponse> endAsync(SOTWeek1ClientSide_TextGame.DungeonGame.endRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://simpleGame/SimpleDungeon/moveRequest", ReplyAction="http://simpleGame/SimpleDungeon/moveResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SOTWeek1ClientSide_TextGame.DungeonGame.moveResponse move(SOTWeek1ClientSide_TextGame.DungeonGame.moveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://simpleGame/SimpleDungeon/moveRequest", ReplyAction="http://simpleGame/SimpleDungeon/moveResponse")]
        System.Threading.Tasks.Task<SOTWeek1ClientSide_TextGame.DungeonGame.moveResponse> moveAsync(SOTWeek1ClientSide_TextGame.DungeonGame.moveRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://simpleGame/SimpleDungeon/isEnemyRequest", ReplyAction="http://simpleGame/SimpleDungeon/isEnemyResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SOTWeek1ClientSide_TextGame.DungeonGame.isEnemyResponse isEnemy(SOTWeek1ClientSide_TextGame.DungeonGame.isEnemyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://simpleGame/SimpleDungeon/isEnemyRequest", ReplyAction="http://simpleGame/SimpleDungeon/isEnemyResponse")]
        System.Threading.Tasks.Task<SOTWeek1ClientSide_TextGame.DungeonGame.isEnemyResponse> isEnemyAsync(SOTWeek1ClientSide_TextGame.DungeonGame.isEnemyRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://simpleGame/SimpleDungeon/getStoryRequest", ReplyAction="http://simpleGame/SimpleDungeon/getStoryResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SOTWeek1ClientSide_TextGame.DungeonGame.getStoryResponse getStory(SOTWeek1ClientSide_TextGame.DungeonGame.getStoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://simpleGame/SimpleDungeon/getStoryRequest", ReplyAction="http://simpleGame/SimpleDungeon/getStoryResponse")]
        System.Threading.Tasks.Task<SOTWeek1ClientSide_TextGame.DungeonGame.getStoryResponse> getStoryAsync(SOTWeek1ClientSide_TextGame.DungeonGame.getStoryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="end", WrapperNamespace="http://simpleGame/", IsWrapped=true)]
    public partial class endRequest {
        
        public endRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="endResponse", WrapperNamespace="http://simpleGame/", IsWrapped=true)]
    public partial class endResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://simpleGame/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public endResponse() {
        }
        
        public endResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="move", WrapperNamespace="http://simpleGame/", IsWrapped=true)]
    public partial class moveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://simpleGame/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public moveRequest() {
        }
        
        public moveRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="moveResponse", WrapperNamespace="http://simpleGame/", IsWrapped=true)]
    public partial class moveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://simpleGame/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public moveResponse() {
        }
        
        public moveResponse(string @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://simpleGame/")]
    public partial class enemy : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private int getLifePointsField;
        
        private int getAttackPointsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int getLifePoints {
            get {
                return this.getLifePointsField;
            }
            set {
                this.getLifePointsField = value;
                this.RaisePropertyChanged("getLifePoints");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int getAttackPoints {
            get {
                return this.getAttackPointsField;
            }
            set {
                this.getAttackPointsField = value;
                this.RaisePropertyChanged("getAttackPoints");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="isEnemy", WrapperNamespace="http://simpleGame/", IsWrapped=true)]
    public partial class isEnemyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://simpleGame/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public isEnemyRequest() {
        }
        
        public isEnemyRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="isEnemyResponse", WrapperNamespace="http://simpleGame/", IsWrapped=true)]
    public partial class isEnemyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://simpleGame/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SOTWeek1ClientSide_TextGame.DungeonGame.enemy @return;
        
        public isEnemyResponse() {
        }
        
        public isEnemyResponse(SOTWeek1ClientSide_TextGame.DungeonGame.enemy @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStory", WrapperNamespace="http://simpleGame/", IsWrapped=true)]
    public partial class getStoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://simpleGame/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public getStoryRequest() {
        }
        
        public getStoryRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getStoryResponse", WrapperNamespace="http://simpleGame/", IsWrapped=true)]
    public partial class getStoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://simpleGame/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getStoryResponse() {
        }
        
        public getStoryResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SimpleDungeonChannel : SOTWeek1ClientSide_TextGame.DungeonGame.SimpleDungeon, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimpleDungeonClient : System.ServiceModel.ClientBase<SOTWeek1ClientSide_TextGame.DungeonGame.SimpleDungeon>, SOTWeek1ClientSide_TextGame.DungeonGame.SimpleDungeon {
        
        public SimpleDungeonClient() {
        }
        
        public SimpleDungeonClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimpleDungeonClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleDungeonClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleDungeonClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOTWeek1ClientSide_TextGame.DungeonGame.endResponse SOTWeek1ClientSide_TextGame.DungeonGame.SimpleDungeon.end(SOTWeek1ClientSide_TextGame.DungeonGame.endRequest request) {
            return base.Channel.end(request);
        }
        
        public string end() {
            SOTWeek1ClientSide_TextGame.DungeonGame.endRequest inValue = new SOTWeek1ClientSide_TextGame.DungeonGame.endRequest();
            SOTWeek1ClientSide_TextGame.DungeonGame.endResponse retVal = ((SOTWeek1ClientSide_TextGame.DungeonGame.SimpleDungeon)(this)).end(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOTWeek1ClientSide_TextGame.DungeonGame.endResponse> SOTWeek1ClientSide_TextGame.DungeonGame.SimpleDungeon.endAsync(SOTWeek1ClientSide_TextGame.DungeonGame.endRequest request) {
            return base.Channel.endAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOTWeek1ClientSide_TextGame.DungeonGame.endResponse> endAsync() {
            SOTWeek1ClientSide_TextGame.DungeonGame.endRequest inValue = new SOTWeek1ClientSide_TextGame.DungeonGame.endRequest();
            return ((SOTWeek1ClientSide_TextGame.DungeonGame.SimpleDungeon)(this)).endAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOTWeek1ClientSide_TextGame.DungeonGame.moveResponse SOTWeek1ClientSide_TextGame.DungeonGame.SimpleDungeon.move(SOTWeek1ClientSide_TextGame.DungeonGame.moveRequest request) {
            return base.Channel.move(request);
        }
        
        public string move(int arg0) {
            SOTWeek1ClientSide_TextGame.DungeonGame.moveRequest inValue = new SOTWeek1ClientSide_TextGame.DungeonGame.moveRequest();
            inValue.arg0 = arg0;
            SOTWeek1ClientSide_TextGame.DungeonGame.moveResponse retVal = ((SOTWeek1ClientSide_TextGame.DungeonGame.SimpleDungeon)(this)).move(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOTWeek1ClientSide_TextGame.DungeonGame.moveResponse> SOTWeek1ClientSide_TextGame.DungeonGame.SimpleDungeon.moveAsync(SOTWeek1ClientSide_TextGame.DungeonGame.moveRequest request) {
            return base.Channel.moveAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOTWeek1ClientSide_TextGame.DungeonGame.moveResponse> moveAsync(int arg0) {
            SOTWeek1ClientSide_TextGame.DungeonGame.moveRequest inValue = new SOTWeek1ClientSide_TextGame.DungeonGame.moveRequest();
            inValue.arg0 = arg0;
            return ((SOTWeek1ClientSide_TextGame.DungeonGame.SimpleDungeon)(this)).moveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOTWeek1ClientSide_TextGame.DungeonGame.isEnemyResponse SOTWeek1ClientSide_TextGame.DungeonGame.SimpleDungeon.isEnemy(SOTWeek1ClientSide_TextGame.DungeonGame.isEnemyRequest request) {
            return base.Channel.isEnemy(request);
        }
        
        public SOTWeek1ClientSide_TextGame.DungeonGame.enemy isEnemy(int arg0) {
            SOTWeek1ClientSide_TextGame.DungeonGame.isEnemyRequest inValue = new SOTWeek1ClientSide_TextGame.DungeonGame.isEnemyRequest();
            inValue.arg0 = arg0;
            SOTWeek1ClientSide_TextGame.DungeonGame.isEnemyResponse retVal = ((SOTWeek1ClientSide_TextGame.DungeonGame.SimpleDungeon)(this)).isEnemy(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOTWeek1ClientSide_TextGame.DungeonGame.isEnemyResponse> SOTWeek1ClientSide_TextGame.DungeonGame.SimpleDungeon.isEnemyAsync(SOTWeek1ClientSide_TextGame.DungeonGame.isEnemyRequest request) {
            return base.Channel.isEnemyAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOTWeek1ClientSide_TextGame.DungeonGame.isEnemyResponse> isEnemyAsync(int arg0) {
            SOTWeek1ClientSide_TextGame.DungeonGame.isEnemyRequest inValue = new SOTWeek1ClientSide_TextGame.DungeonGame.isEnemyRequest();
            inValue.arg0 = arg0;
            return ((SOTWeek1ClientSide_TextGame.DungeonGame.SimpleDungeon)(this)).isEnemyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOTWeek1ClientSide_TextGame.DungeonGame.getStoryResponse SOTWeek1ClientSide_TextGame.DungeonGame.SimpleDungeon.getStory(SOTWeek1ClientSide_TextGame.DungeonGame.getStoryRequest request) {
            return base.Channel.getStory(request);
        }
        
        public string getStory(int arg0) {
            SOTWeek1ClientSide_TextGame.DungeonGame.getStoryRequest inValue = new SOTWeek1ClientSide_TextGame.DungeonGame.getStoryRequest();
            inValue.arg0 = arg0;
            SOTWeek1ClientSide_TextGame.DungeonGame.getStoryResponse retVal = ((SOTWeek1ClientSide_TextGame.DungeonGame.SimpleDungeon)(this)).getStory(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOTWeek1ClientSide_TextGame.DungeonGame.getStoryResponse> SOTWeek1ClientSide_TextGame.DungeonGame.SimpleDungeon.getStoryAsync(SOTWeek1ClientSide_TextGame.DungeonGame.getStoryRequest request) {
            return base.Channel.getStoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOTWeek1ClientSide_TextGame.DungeonGame.getStoryResponse> getStoryAsync(int arg0) {
            SOTWeek1ClientSide_TextGame.DungeonGame.getStoryRequest inValue = new SOTWeek1ClientSide_TextGame.DungeonGame.getStoryRequest();
            inValue.arg0 = arg0;
            return ((SOTWeek1ClientSide_TextGame.DungeonGame.SimpleDungeon)(this)).getStoryAsync(inValue);
        }
    }
}
